name: test
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hiii"
      - name: Print goodbye
        run: echo "Byyye"
      
